/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Wed, May 28, 2008                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :SH7264                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x4000         /* Do not modify this line. */
