//
///	コード量削減のため、未使用割り込みはすべてDummy()のエイリアスにする.
//

#define INT_TRAPA32 Dummy
#define INT_TRAPA33 Dummy
#define INT_TRAPA34 Dummy
#define INT_TRAPA35 Dummy
#define INT_TRAPA36 Dummy
#define INT_TRAPA37 Dummy
#define INT_TRAPA38 Dummy
#define INT_TRAPA39 Dummy
#define INT_TRAPA40 Dummy
#define INT_TRAPA41 Dummy
#define INT_TRAPA42 Dummy
#define INT_TRAPA43 Dummy
#define INT_TRAPA44 Dummy
#define INT_TRAPA45 Dummy
#define INT_TRAPA46 Dummy
#define INT_TRAPA47 Dummy
#define INT_TRAPA48 Dummy
#define INT_TRAPA49 Dummy
#define INT_TRAPA50 Dummy
#define INT_TRAPA51 Dummy
#define INT_TRAPA52 Dummy
#define INT_TRAPA53 Dummy
#define INT_TRAPA54 Dummy
#define INT_TRAPA55 Dummy
#define INT_TRAPA56 Dummy
#define INT_TRAPA57 Dummy
#define INT_TRAPA58 Dummy
#define INT_TRAPA59 Dummy
#define INT_TRAPA60 Dummy
#define INT_TRAPA61 Dummy
#define INT_TRAPA62 Dummy
#define INT_TRAPA63 Dummy
#define INT_IRQ_IRQ0 Dummy
#define INT_IRQ_IRQ1 Dummy
#define INT_IRQ_IRQ2 Dummy
#define INT_IRQ_IRQ3 Dummy
#define INT_IRQ_IRQ4 Dummy
#define INT_IRQ_IRQ5 Dummy
#define INT_IRQ_IRQ6 Dummy
#define INT_IRQ_IRQ7 Dummy
#define INT_PINT_PINT0 Dummy
#define INT_PINT_PINT1 Dummy
#define INT_PINT_PINT2 Dummy
#define INT_PINT_PINT3 Dummy
#define INT_PINT_PINT4 Dummy
#define INT_PINT_PINT5 Dummy
#define INT_PINT_PINT6 Dummy
#define INT_PINT_PINT7 Dummy
#define INT_DMAC0_DEI0 Dummy
#define INT_DMAC0_HEI0 Dummy
#define INT_DMAC1_DEI1 Dummy
#define INT_DMAC1_HEI1 Dummy
#define INT_DMAC2_DEI2 Dummy
#define INT_DMAC2_HEI2 Dummy
#define INT_DMAC3_DEI3 Dummy
#define INT_DMAC3_HEI3 Dummy
#define INT_DMAC4_DEI4 Dummy
#define INT_DMAC4_HEI4 Dummy
#define INT_DMAC5_HEI5 Dummy
#define INT_DMAC6_HEI6 Dummy
#define INT_DMAC7_DEI7 Dummy
#define INT_DMAC7_HEI7 Dummy
#define INT_DMAC8_DEI8 Dummy
#define INT_DMAC8_HEI8 Dummy
#define INT_DMAC9_DEI9 Dummy
#define INT_DMAC9_HEI9 Dummy
#define INT_DMAC10_DEI10 Dummy
#define INT_DMAC10_HEI10 Dummy
#define INT_DMAC11_DEI11 Dummy
#define INT_DMAC11_HEI11 Dummy
#define INT_DMAC12_DEI12 Dummy
#define INT_DMAC12_HEI12 Dummy
#define INT_DMAC13_DEI13 Dummy
#define INT_DMAC13_HEI13 Dummy
#define INT_DMAC14_DEI14 Dummy
#define INT_DMAC14_HEI14 Dummy
#define INT_DMAC15_DEI15 Dummy
#define INT_DMAC15_HEI15 Dummy
#define INT_VDC3_VIVSYNCJ Dummy
#define INT_VDC3_VBUFERR Dummy
#define INT_VDC3_VIFIELDE Dummy
#define INT_VDC3_VOLINE Dummy
#define INT_CMT1_CMI1 Dummy
#define INT_BSC_CMI Dummy
#define INT_WDT_ITI Dummy
#define INT_MTU2_TGI0A Dummy
#define INT_MTU2_TGI0B Dummy
#define INT_MTU2_TGI0C Dummy
#define INT_MTU2_TGI0D Dummy
#define INT_MTU2_TCI0V Dummy
#define INT_MTU2_TGI0E Dummy
#define INT_MTU2_TGI0F Dummy
#define INT_MTU2_TGI1A Dummy
#define INT_MTU2_TGI1B Dummy
#define INT_MTU2_TCI1V Dummy
#define INT_MTU2_TCI1U Dummy
#define INT_MTU2_TGI2A Dummy
#define INT_MTU2_TGI2B Dummy
#define INT_MTU2_TCI2V Dummy
#define INT_MTU2_TCI2U Dummy
#define INT_MTU2_TGI3A Dummy
#define INT_MTU2_TGI3B Dummy
#define INT_MTU2_TGI3C Dummy
#define INT_MTU2_TGI3D Dummy
#define INT_MTU2_TCI3V Dummy
#define INT_MTU2_TGI4A Dummy
#define INT_MTU2_TGI4B Dummy
#define INT_MTU2_TGI4C Dummy
#define INT_MTU2_TGI4D Dummy
#define INT_MTU2_TCI4V Dummy
#define INT_PWM1 Dummy
#define INT_PWM2 Dummy
#define INT_AD_ADI Dummy
#define INT_SSI0_SSIF0 Dummy
#define INT_SSI0_SSIRXI0 Dummy
#define INT_SSI0_SSITXI0 Dummy
#define INT_SSI1_SSII1 Dummy
#define INT_SSI1_SSIRTI1 Dummy
#define INT_SSI2_SSII2 Dummy
#define INT_SSI2_SSIRTI2 Dummy
#define INT_SSI3_SSII3 Dummy
#define INT_SSI3_SSIRTI3 Dummy
#define INT_SPDIF_SPDIFI Dummy
#define INT_IIC3_STPI0 Dummy
#define INT_IIC3_NAKI0 Dummy
#define INT_IIC3_RXI0 Dummy
#define INT_IIC3_TXI0 Dummy
#define INT_IIC3_TEI0 Dummy
#define INT_IIC3_STPI1 Dummy
#define INT_IIC3_NAKI1 Dummy
#define INT_IIC3_RXI1 Dummy
#define INT_IIC3_TXI1 Dummy
#define INT_IIC3_TEI1 Dummy
#define INT_IIC3_STPI2 Dummy
#define INT_IIC3_NAKI2 Dummy
#define INT_IIC3_RXI2 Dummy
#define INT_IIC3_TXI2 Dummy
#define INT_IIC3_TEI2 Dummy
#define INT_SCIF0_BRI0 Dummy
#define INT_SCIF0_ERI0 Dummy
#define INT_SCIF0_RXI0 Dummy
#define INT_SCIF0_TXI0 Dummy
#define INT_SCIF1_BRI1 Dummy
#define INT_SCIF1_ERI1 Dummy
#define INT_SCIF1_RXI1 Dummy
#define INT_SCIF1_TXI1 Dummy
#define INT_SCIF2_BRI2 Dummy
#define INT_SCIF2_ERI2 Dummy
#define INT_SCIF2_RXI2 Dummy
#define INT_SCIF2_TXI2 Dummy
#define INT_SCIF3_BRI3 Dummy
#define INT_SCIF3_ERI3 Dummy
#define INT_SCIF3_RXI3 Dummy
#define INT_SCIF3_TXI3 Dummy
#define INT_SCIF4_BRI4 Dummy
#define INT_SCIF4_ERI4 Dummy
#define INT_SCIF4_RXI4 Dummy
#define INT_SCIF4_TXI4 Dummy
#define INT_SCIF5_BRI5 Dummy
#define INT_SCIF5_ERI5 Dummy
#define INT_SCIF5_RXI5 Dummy
#define INT_SCIF5_TXI5 Dummy
#define INT_SCIF6_BRI6 Dummy
#define INT_SCIF6_ERI6 Dummy
#define INT_SCIF6_RXI6 Dummy
#define INT_SCIF6_TXI6 Dummy
#define INT_SCIF7_BRI7 Dummy
#define INT_SCIF7_ERI7 Dummy
#define INT_SCIF7_RXI7 Dummy
#define INT_SCIF7_TXI7 Dummy
#define INT_SIOF_SIOFI Dummy
#define INT_RSPI0_SPEI0 Dummy
#define INT_RSPI0_SPRI0 Dummy
#define INT_RSPI0_SPTI0 Dummy
#define INT_RSPI1_SPEI1 Dummy
#define INT_RSPI1_SPRI1 Dummy
#define INT_RSPI1_SPTI1 Dummy
#define INT_RCAN0_ERS0 Dummy
#define INT_RCAN0_OVR0 Dummy
#define INT_RCAN0_RM00 Dummy
#define INT_RCAN0_RM10 Dummy
#define INT_RCAN0_SLE0 Dummy
#define INT_RCAN1_ERS1 Dummy
#define INT_RCAN1_OVR1 Dummy
#define INT_RCAN1_RM01 Dummy
#define INT_RCAN1_RM11 Dummy
#define INT_RCAN1_SLE1 Dummy
#define INT_IEB_IEB Dummy
#define INT_ROMDEC_ISY Dummy
#define INT_ROMDEC_IERR Dummy
#define INT_ROMDEC_ITARG Dummy
#define INT_ROMDEC_ISEC Dummy
#define INT_ROMDEC_IBUF Dummy
#define INT_ROMDEC_IREADY Dummy
#define INT_FLCTL_FLSTEI Dummy
#define INT_FLCTL_FLTENDI Dummy
#define INT_FLCTL_FLTREQ0I Dummy
#define INT_FLCTL_FLTREQ1I Dummy
#define INT_SDHI_SDHI3 Dummy
#define INT_SDHI_SDHI0 Dummy
#define INT_SDHI_SDHI1 Dummy
#define INT_RTC_ARM Dummy
#define INT_RTC_PRD Dummy
#define INT_RTC_CUP Dummy
#define INT_SRC0_OVF0 Dummy
#define INT_SRC0_UDF0 Dummy
#define INT_SRC0_CEF0 Dummy
#define INT_SRC0_ODFI0 Dummy
#define INT_SRC0_IDEI0 Dummy
#define INT_SRC1_OVF1 Dummy
#define INT_SRC1_UDF1 Dummy
#define INT_SRC1_CEF1 Dummy
#define INT_SRC1_ODFI1 Dummy
#define INT_SRC1_IDEI1 Dummy
#define INT_DCU_DCUEI Dummy
#define INT_DCU_OFFI Dummy
#define INT_DCU_IFEI Dummy
